# This workflow builds a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
#
# We use it for testing the IRuta build process and its Unit tests.

name: Gradle Build and Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build IRuta (also executes JUnit tests)
      uses: eskatos/gradle-command-action@v1
      with:
         gradle-version: 4.8.1
         arguments: build
