# This workflow builds a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
#
# We use it for testing the IRuta build process and its Unit tests.

name: Gradle Build and Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 8
        
    - name: Build IRuta using Gradle (with JUnit tests)
      uses: gradle/gradle-build-action@v2
      with:
         gradle-version: 4.8.1
         arguments: build --info
